        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 15 20:00:05 2015
        MODULE FIND_MORTALITY_TREND_mod
          INTERFACE 
            SUBROUTINE FIND_MORTALITY_TREND
            END SUBROUTINE FIND_MORTALITY_TREND
          END INTERFACE 
        END MODULE FIND_MORTALITY_TREND_mod
