        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 15 20:00:06 2015
        MODULE OPENFILES_mod
          INTERFACE 
            SUBROUTINE OPENFILES
            END SUBROUTINE OPENFILES
          END INTERFACE 
        END MODULE OPENFILES_mod
