        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 15 20:00:06 2015
        MODULE READ_CAUSE_DEATH_FILES_mod
          INTERFACE 
            SUBROUTINE READ_CAUSE_DEATH_FILES
            END SUBROUTINE READ_CAUSE_DEATH_FILES
          END INTERFACE 
        END MODULE READ_CAUSE_DEATH_FILES_mod
