        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 15 19:33:42 2015
        MODULE EXTEND_SSA_MORTALITY_mod
          INTERFACE 
            SUBROUTINE EXTEND_SSA_MORTALITY
            END SUBROUTINE EXTEND_SSA_MORTALITY
          END INTERFACE 
        END MODULE EXTEND_SSA_MORTALITY_mod
