        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 15 19:33:41 2015
        MODULE OPENFILES_mod
          INTERFACE 
            SUBROUTINE OPENFILES
            END SUBROUTINE OPENFILES
          END INTERFACE 
        END MODULE OPENFILES_mod
